# Generated by Django 3.0.6 on 2020-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_city_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='Oregon', max_length=100),
            preserve_default=False,
        ),
    ]
