# Generated by Django 3.0.6 on 2020-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_auto_20200923_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favorite_color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
